### ISSUE TITLE
TypeError: config is undefined

### ISSUE THREAD

**Issue by utf-4096** [pkg93/pkg93#1]
![image](https://user-images.githubusercontent.com/25370216/38635826-ddbac266-3dc6-11e8-9773-f34f3af04939.png)
Looks like this happens only on first run, you might wanna make something to init files to prevent doing this.

**Comment by 1024x2** [comment]
Can confirm. Working on a fix.

**Comment by 1024x2** [comment]
Should be solved in v1.1.2.
